   # 《Python编程入门》08 模块与包、正则表达式
   
   ***

<img width=1200 height=480 src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1550608634102&di=50b3b0f113ad9adbf28bfc64dde1ff1f&imgtype=0&src=http%3A%2F%2Fimg95.699pic.com%2Fphoto%2F50062%2F4783.jpg_wh860.jpg"/>

## =^^=author:秋叶为何而落 =^=^=^= QQ : 81502787 =^^=

   # 1.numpy的使用
    安装：pip install numpy

In [3]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [4]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
b.ndim
b.shape

(3, 2)

In [7]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
d = np.linspace(0, 3, 11)
print(d)

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3. ]


In [10]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
f = np.random.randint(1, 5, 20).reshape(4, 5)
print(f)

[[4 3 3 4 2]
 [1 4 3 2 1]
 [1 2 1 2 2]
 [1 2 2 2 2]]


# 正则表达式